### ISSUE TITLE
Many errors post-install

### ISSUE THREAD

**Issue by Nicolas-GE** [jingkaimori/midieditor#2]
when installed, these errors show up

1. The code execution cannot proceed because libgcc_s_seh-1.dll was not found. Reinstalling the program may fix this problem. 

2. same as 1

3. The code execution cannot proceed because libstdc++-6.dll was not found. Reinstalling the program may fix this problem. 

4. same as 3

**Comment by aleph23** [comment]
Same.

**Comment by jingkaimori** [comment]
That's because old install script manually copy lib file into pack, so some dependency is omitted. Now github action (workflow) artifacts contains enough file.

**Comment by ItsLemmy** [comment]
what a show stopper...

**Comment by jingkaimori** [comment]
@quadbyte @aleph23 @Nicolas-GE New version packed with qtifw is published

**Comment by jingkaimori** [comment]
New installer proved to work fine, close this issue. If any errors were found, please reopen it.
